/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YazOkuluRouteImport } from './routes/yaz-okulu'
import { Route as ProgramlarRouteImport } from './routes/programlar'
import { Route as OkulGezileriRouteImport } from './routes/okul-gezileri'
import { Route as MekanlarRouteImport } from './routes/mekanlar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkindaRouteImport } from './routes/hakkinda'
import { Route as EtkinliklerRouteImport } from './routes/etkinlikler'
import { Route as EducereAtolyeleriRouteImport } from './routes/educere-atolyeleri'
import { Route as AtolyelerRouteImport } from './routes/atolyeler'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramlarSlugRouteImport } from './routes/programlar.$slug'
import { Route as MekanlarSlugRouteImport } from './routes/mekanlar.$slug'
import { Route as AtolyelerSlugRouteImport } from './routes/atolyeler.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const YazOkuluRoute = YazOkuluRouteImport.update({
  id: '/yaz-okulu',
  path: '/yaz-okulu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlarRoute = ProgramlarRouteImport.update({
  id: '/programlar',
  path: '/programlar',
  getParentRoute: () => rootRouteImport,
} as any)
const OkulGezileriRoute = OkulGezileriRouteImport.update({
  id: '/okul-gezileri',
  path: '/okul-gezileri',
  getParentRoute: () => rootRouteImport,
} as any)
const MekanlarRoute = MekanlarRouteImport.update({
  id: '/mekanlar',
  path: '/mekanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkindaRoute = HakkindaRouteImport.update({
  id: '/hakkinda',
  path: '/hakkinda',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinliklerRoute = EtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => rootRouteImport,
} as any)
const EducereAtolyeleriRoute = EducereAtolyeleriRouteImport.update({
  id: '/educere-atolyeleri',
  path: '/educere-atolyeleri',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyelerRoute = AtolyelerRouteImport.update({
  id: '/atolyeler',
  path: '/atolyeler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlarSlugRoute = ProgramlarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramlarRoute,
} as any)
const MekanlarSlugRoute = MekanlarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MekanlarRoute,
} as any)
const AtolyelerSlugRoute = AtolyelerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AtolyelerRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atolyeler': typeof AtolyelerRouteWithChildren
  '/educere-atolyeleri': typeof EducereAtolyeleriRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/mekanlar': typeof MekanlarRouteWithChildren
  '/okul-gezileri': typeof OkulGezileriRoute
  '/programlar': typeof ProgramlarRouteWithChildren
  '/yaz-okulu': typeof YazOkuluRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atolyeler/$slug': typeof AtolyelerSlugRoute
  '/mekanlar/$slug': typeof MekanlarSlugRoute
  '/programlar/$slug': typeof ProgramlarSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atolyeler': typeof AtolyelerRouteWithChildren
  '/educere-atolyeleri': typeof EducereAtolyeleriRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/mekanlar': typeof MekanlarRouteWithChildren
  '/okul-gezileri': typeof OkulGezileriRoute
  '/programlar': typeof ProgramlarRouteWithChildren
  '/yaz-okulu': typeof YazOkuluRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atolyeler/$slug': typeof AtolyelerSlugRoute
  '/mekanlar/$slug': typeof MekanlarSlugRoute
  '/programlar/$slug': typeof ProgramlarSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/atolyeler': typeof AtolyelerRouteWithChildren
  '/educere-atolyeleri': typeof EducereAtolyeleriRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
  '/login': typeof LoginRoute
  '/mekanlar': typeof MekanlarRouteWithChildren
  '/okul-gezileri': typeof OkulGezileriRoute
  '/programlar': typeof ProgramlarRouteWithChildren
  '/yaz-okulu': typeof YazOkuluRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/atolyeler/$slug': typeof AtolyelerSlugRoute
  '/mekanlar/$slug': typeof MekanlarSlugRoute
  '/programlar/$slug': typeof ProgramlarSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atolyeler'
    | '/educere-atolyeleri'
    | '/etkinlikler'
    | '/hakkinda'
    | '/iletisim'
    | '/login'
    | '/mekanlar'
    | '/okul-gezileri'
    | '/programlar'
    | '/yaz-okulu'
    | '/admin'
    | '/atolyeler/$slug'
    | '/mekanlar/$slug'
    | '/programlar/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atolyeler'
    | '/educere-atolyeleri'
    | '/etkinlikler'
    | '/hakkinda'
    | '/iletisim'
    | '/login'
    | '/mekanlar'
    | '/okul-gezileri'
    | '/programlar'
    | '/yaz-okulu'
    | '/admin'
    | '/atolyeler/$slug'
    | '/mekanlar/$slug'
    | '/programlar/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atolyeler'
    | '/educere-atolyeleri'
    | '/etkinlikler'
    | '/hakkinda'
    | '/iletisim'
    | '/login'
    | '/mekanlar'
    | '/okul-gezileri'
    | '/programlar'
    | '/yaz-okulu'
    | '/_authenticated/admin'
    | '/atolyeler/$slug'
    | '/mekanlar/$slug'
    | '/programlar/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtolyelerRoute: typeof AtolyelerRouteWithChildren
  EducereAtolyeleriRoute: typeof EducereAtolyeleriRoute
  EtkinliklerRoute: typeof EtkinliklerRoute
  HakkindaRoute: typeof HakkindaRoute
  IletisimRoute: typeof IletisimRoute
  LoginRoute: typeof LoginRoute
  MekanlarRoute: typeof MekanlarRouteWithChildren
  OkulGezileriRoute: typeof OkulGezileriRoute
  ProgramlarRoute: typeof ProgramlarRouteWithChildren
  YazOkuluRoute: typeof YazOkuluRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaz-okulu': {
      id: '/yaz-okulu'
      path: '/yaz-okulu'
      fullPath: '/yaz-okulu'
      preLoaderRoute: typeof YazOkuluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlar': {
      id: '/programlar'
      path: '/programlar'
      fullPath: '/programlar'
      preLoaderRoute: typeof ProgramlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okul-gezileri': {
      id: '/okul-gezileri'
      path: '/okul-gezileri'
      fullPath: '/okul-gezileri'
      preLoaderRoute: typeof OkulGezileriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mekanlar': {
      id: '/mekanlar'
      path: '/mekanlar'
      fullPath: '/mekanlar'
      preLoaderRoute: typeof MekanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkinda': {
      id: '/hakkinda'
      path: '/hakkinda'
      fullPath: '/hakkinda'
      preLoaderRoute: typeof HakkindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlikler': {
      id: '/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/etkinlikler'
      preLoaderRoute: typeof EtkinliklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educere-atolyeleri': {
      id: '/educere-atolyeleri'
      path: '/educere-atolyeleri'
      fullPath: '/educere-atolyeleri'
      preLoaderRoute: typeof EducereAtolyeleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolyeler': {
      id: '/atolyeler'
      path: '/atolyeler'
      fullPath: '/atolyeler'
      preLoaderRoute: typeof AtolyelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlar/$slug': {
      id: '/programlar/$slug'
      path: '/$slug'
      fullPath: '/programlar/$slug'
      preLoaderRoute: typeof ProgramlarSlugRouteImport
      parentRoute: typeof ProgramlarRoute
    }
    '/mekanlar/$slug': {
      id: '/mekanlar/$slug'
      path: '/$slug'
      fullPath: '/mekanlar/$slug'
      preLoaderRoute: typeof MekanlarSlugRouteImport
      parentRoute: typeof MekanlarRoute
    }
    '/atolyeler/$slug': {
      id: '/atolyeler/$slug'
      path: '/$slug'
      fullPath: '/atolyeler/$slug'
      preLoaderRoute: typeof AtolyelerSlugRouteImport
      parentRoute: typeof AtolyelerRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AtolyelerRouteChildren {
  AtolyelerSlugRoute: typeof AtolyelerSlugRoute
}

const AtolyelerRouteChildren: AtolyelerRouteChildren = {
  AtolyelerSlugRoute: AtolyelerSlugRoute,
}

const AtolyelerRouteWithChildren = AtolyelerRoute._addFileChildren(
  AtolyelerRouteChildren,
)

interface MekanlarRouteChildren {
  MekanlarSlugRoute: typeof MekanlarSlugRoute
}

const MekanlarRouteChildren: MekanlarRouteChildren = {
  MekanlarSlugRoute: MekanlarSlugRoute,
}

const MekanlarRouteWithChildren = MekanlarRoute._addFileChildren(
  MekanlarRouteChildren,
)

interface ProgramlarRouteChildren {
  ProgramlarSlugRoute: typeof ProgramlarSlugRoute
}

const ProgramlarRouteChildren: ProgramlarRouteChildren = {
  ProgramlarSlugRoute: ProgramlarSlugRoute,
}

const ProgramlarRouteWithChildren = ProgramlarRoute._addFileChildren(
  ProgramlarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtolyelerRoute: AtolyelerRouteWithChildren,
  EducereAtolyeleriRoute: EducereAtolyeleriRoute,
  EtkinliklerRoute: EtkinliklerRoute,
  HakkindaRoute: HakkindaRoute,
  IletisimRoute: IletisimRoute,
  LoginRoute: LoginRoute,
  MekanlarRoute: MekanlarRouteWithChildren,
  OkulGezileriRoute: OkulGezileriRoute,
  ProgramlarRoute: ProgramlarRouteWithChildren,
  YazOkuluRoute: YazOkuluRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
